### PR TITLE
Remove Privacy Badger as we already have uBlock Origin

### PR DESCRIPTION
**Pull request by cypherpunk-institute**
The Privacy Badger vastly overlaps with uBlock Origin. The net gain is negligible while significant risk is being introduced by any next browser plugin (could get hijacked etc). Also, the two plugins were not designed to work together and can interact in unexpected ways. Less is more. For details search /r/privacytoolsio community.

### CODE REVIEW

**Comment by krakensecuritylabs** [comment]
Thanks!

While we acknowledge that there is overlap between the two and that less is generally more, we're not convinced that there is "vast" overlap and significant risk to using both. We briefly browsed the subreddit and other areas but couldn't find definitive evidence of these claims. Could you share more information to convince us?

**Comment by cypherpunk-institute** [comment]
Please note Firefox, Brave etc already have a pretty decent built-in privacy protections (tracker removal etc). uBlock improves on this. With Privacy Badger we have 3 tools for the same job in these browsers.

As every plugin is really a "root in the browser" that gets automatically and often updated from potentially compromised upstream, it is critical to have virtually zero plugins. There were instances of popular extensions compromised (not by the authors) to steal cryptocurrency by replacing addresses etc.

**Comment by krakensecuritylabs** [comment]
What do you make of the advice from PB that recommends using them together? https://www.eff.org/tr/privacybadger/faq#Is-Privacy-Badger-compatible-with-other-extensions,-including-other-adblockers

Obviously, the PB authors probably have some bias, but the EFF is typically trustworthy.

**Comment by krakensecuritylabs** [comment]
No response. Closing.

**Pull request closed without merging**
